title: Hyperledger Caliper
description: >-
  Caliper is a blockchain performance benchmark framework, which allows users to
  test different blockchain solutions with predefined use cases, and get a set
  of performance test results.
url: 'https://hyperledger.github.io'
baseurl: /caliper
repository: hyperledger/caliper
repo: caliper
caliper:
  v0_2: v0.2/
  current_release: v0.3.2/
  next_release: vNext/
  v0_3_2: v0.3.2/
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
categories:
  - docs
collections:
  docs:
    output: true
    permalink: '/:collection/:path/'
