---
test:
  name: simple
  description: This is an example benchmark for caliper
  clients:
    type: local
    number: 1
  rounds:
  - label: open
    txNumber:
    - 50
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      money: 10000
      txnPerBatch: 10
    callback: benchmark/simple/open.js
  - label: query
    txNumber:
    - 5
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: benchmark/simple/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
