#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    txDuration:
    - 30
    rateControl:
    - type: composite-rate
      opts:
        weights:
        - 10
        - 5
        - 5
        - 10
        rateControllers:
        - type: fixed-rate
          opts:
            tps: 20
        - type: fixed-rate
          opts:
            tps: 40
        - type: zero-rate
          opts: {}
        - type: fixed-rate
          opts:
            tps: 30
        logChange: true
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
observer:
  interval: 1
  type: local
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
