global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: 'prometheus'

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
    - targets: ['prometheus:9090', 'pushGateway:9091']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']
