---
blockchain:
  type: fabric
  config: benchmark/simple/fabric.json
command:
  start: docker-compose -f network/fabric/2org2peer/docker-compose.yaml up -d
  end: docker-compose -f network/fabric/2org2peer/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q)
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    txNumber:
    - 5000
    rateControl:
    - type: fixed-feedback-rate
      opts:
        tps: 100
        sleep_time: 1000
        unfinished_per_client: 10
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: query
    txNumber:
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 300
    - type: fixed-rate
      opts:
        tps: 400
    callback: benchmark/simple/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
