#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
    workers:
        type: local
        number: 2
    rounds:
    - label: init1
      txNumber: 25
      rateControl: { type: 'fixed-rate', opts: { tps: 5 } }
      callback: ../init.js
    - label: query
      txNumber: 25
      rateControl: { type: 'linear-rate', opts: { startingTps: 5, finishingTps: 10 } }
      callback: ../query.js
observer:
    interval: 1
    type: prometheus
monitor:
    interval: 1
    type: ['prometheus']
    prometheus:
        url: "http://localhost:9090"
        push_url: "http://localhost:9091"
        metrics:
            ignore: [prometheus, pushGateway, cadvisor, grafana, node-exporter]
            include:
                Endorse Time (s):
                    query: rate(endorser_propsal_duration_sum{chaincode="marbles:v0"}[1m])/rate(endorser_propsal_duration_count{chaincode="marbles:v0"}[1m])
                    step: 1
                    label: instance
                    statistic: avg
                Max Memory (MB):
                    query: sum(container_memory_rss{name=~".+"}) by (name)
                    step: 10
                    label: name
                    statistic: max
                    multiplier: 0.000001
        charting:
            polar:
                metrics: [Max Memory (MB)]
            bar:
                metrics: [all]
