name: CI (PR)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  dci-lint:
    uses: ./.github/workflows/dci.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    needs: unit-tests
